### ISSUE TITLE
COMPILE ERROR

### ISSUE THREAD

**Issue by cymqqqq** [Patryk27/shorelark#1]
Compiling serde_json v1.0.59
error[E0658]: use of unstable library feature 'btreemap_remove_entry'
How can I fix this problem?

**Comment by Patryk27** [comment]
Could try compiling with nightly Rust (i.e. `rustup default nightly`, and then re-compile)?

**Comment by cymqqqq** [comment]
I try to compile with 'rustup default nightly', but more errors exists:
error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\sgemm_kernel.rs:473:44
    |
473 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                            ^^

error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\sgemm_kernel.rs:473:39
    |
473 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                       ^^

error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\dgemm_kernel.rs:786:44
    |
786 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                            ^^

error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\dgemm_kernel.rs:786:39
    |
786 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                       ^^

error: aborting due to 4 previous errors

error: could not compile `matrixmultiply`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Patryk27** [comment]
I've just pushed a few commits - could you try again? :-) Seems like it should all work now.

**Comment by cymqqqq** [comment]
Same errors for both methods "rustup default nightly" & "the original"
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling serde_json v1.0.59
error[E0658]: use of unstable library feature 'btreemap_remove_entry'
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_json-1.0.59\src\map.rs:136:25
    |
136 |         return self.map.remove_entry(key);

[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling matrixmultiply v0.2.3
   Compiling syn v1.0.51
   Compiling num-traits v0.2.14
   Compiling generic-array v0.14.4
error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\sgemm_kernel.rs:473:44
    |
473 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                            ^^

error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\sgemm_kernel.rs:473:39
    |
473 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                       ^^

error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\dgemm_kernel.rs:786:44
    |
786 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                            ^^

error: array lengths can't depend on generic parameters
   --> C:\Users\cym\.cargo\registry\src\github.com-1ecc6299db9ec823\matrixmultiply-0.2.3\src\dgemm_kernel.rs:786:39
    |
786 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |

**Comment by Patryk27** [comment]
Hm, that's weird - could you post results of `cargo --version`, `rustc --version` and `rustup --version`?

**Comment by cymqqqq** [comment]
cargo 1.44.1 (88ba85757 2020-06-11)
rustc 1.44.1 (c7087fe00 2020-06-17)
rustup 1.21.1 (7832b2ebe 2019-12-20)

**Comment by Patryk27** [comment]
Ah, yes - that's an older version of the compiler; `rustup update` should get us going :-)

**Comment by cymqqqq** [comment]
Yeah, I update rustup, then I try to recompile with "rustup default nightly", and it works.
really thank U a lot.

**Comment by Patryk27** [comment]
No problem, thanks for reporting - I’ve gotta add the compiler version to readme.
