### ISSUE TITLE
Error in the web part

### ISSUE THREAD

**Issue by yovanoc** [Patryk27/shorelark#10]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/7302317/226483981-b79e84ce-42ba-48b5-a92c-f295074c0fb7.png">

**Comment by yovanoc** [comment]
Upgrading to webpack 5 fixed this.

**Comment by Patryk27** [comment]
It looks like the newest wasm-pack generates code that's not compatible with the older Webpack here - thanks for bringing it to my attention, I'll try to upgrade the toolchain and dependencies tomorrow, this should bring the repository back to being plug-and-play 🙂

**Comment by Patryk27** [comment]
Okie, I've upgraded the project to newest Rust & Webpack 🙂
