### ISSUE TITLE
Angles problems?

### ISSUE THREAD

**Issue by yovanoc** [Patryk27/shorelark#11]
I convert the web pack app part into a vite/react-ts project then try to play a bit with the code and found an interesting thing.

![image](https://user-images.githubusercontent.com/7302317/226737622-08b34384-a61a-4910-978a-dce55d5a08d4.png)

PS: I changed to fov angle to PI/2 but that's not the point.

I try to render the fov because your 'arcs' seems a bit off and here's what I saw.

It comes from this part

<img width="637" alt="image" src="https://user-images.githubusercontent.com/7302317/226737857-97a19423-6240-448e-b6ea-ffbcddd9dd78.png">

I don't know why you added `Math.PI / 2.0` here ? probably because otherwise we see the fov on the side and not in front of them, but IT REALLY is on the side, you can look with your drawn arcs and this is why birds are constantly turning.

**Comment by yovanoc** [comment]
And I would like to add that if I follow your rules for the -sin +cos thing we have a nice render but we can clearly see that the food perception is not based on these calculations:

![image](https://user-images.githubusercontent.com/7302317/227221958-b0d388ff-c83d-48ad-b20d-050255b0e4e6.png)

my repo: https://github.com/yovanoc/mysim

**Comment by Patryk27** [comment]
Oh, that's a nice find - I'll take a look later and try to remind what's going on; I swear angles are a hill I'm going to die on 😅

**Comment by yovanoc** [comment]
Yeah adding this fov representation helped me a lot to catch this. I first saw that your arc shapes are not faced to food then I dig with these things. You can try on my repo, I added a mouse hover on birds to debug too. 
But yeah if we remove these Math.PI / 2 the representation of the vision appears to be good but then I asked myself if these birds are not flying from the side like crabs 😂 , I'm with you with these angles!

**Comment by yovanoc** [comment]
I look back your tuto again.

<img width="990" alt="image" src="https://user-images.githubusercontent.com/7302317/227716830-a34c165f-de83-4c7b-b2ba-efadf1268461.png">

 pi / 2 is not faced to the right if I understand well so this the eye implementation and all tests that are not correct ?

**Comment by Patryk27** [comment]
Note that `fov_angle` corresponds to _how wide_ an eye sees - and so `fov_angle of 2PI` = the bird sees everything around it, while `fov_angle of PI / 2` = the bird sees 90° "cone" in front of it; it's not related to the direction / rotation 👀

**Comment by yovanoc** [comment]
Yes sorry I didn't express myself correctly. The thing I wanna said is that for this test `rot: 0` and for a fov angle of PI/2, this is not this result because you said rot 0 is faced to the upward direction no ? 

```
    /// ------------
    /// |        /.|
    /// |      /...|
    /// |    @>...%|
    /// |      \...|
    /// |        \.|
    /// ------------
 ```

**Comment by yovanoc** [comment]
Oh no mb you said it was counter clockwise ! I really don't know then.. but there is an issue for sure between the eye.rs file and the things we tried to render

**Comment by Patryk27** [comment]
Okie, so eyes themselves seem to be correct - it's rest of the code that uses _funky angles_, and applying this:
```diff
diff --git a/libs/simulation/src/animal.rs b/libs/simulation/src/animal.rs
index a7e65dd..436949e 100644
--- a/libs/simulation/src/animal.rs
+++ b/libs/simulation/src/animal.rs
@@ -56,7 +56,7 @@ impl Animal {
     }
 
     pub(crate) fn process_movement(&mut self) {
-        self.position += self.rotation * na::Vector2::new(0.0, self.speed);
+        self.position += self.rotation * na::Vector2::new(self.speed, 0.0);
         self.position.x = na::wrap(self.position.x, 0.0, 1.0);
         self.position.y = na::wrap(self.position.y, 0.0, 1.0);
     }
diff --git a/www/index.js b/www/index.js
index 9b8c02b..354fca6 100644
--- a/www/index.js
+++ b/www/index.js
@@ -261,7 +261,7 @@ function redraw() {
             animal.x,
             animal.y,
             config.food_size,
-            animal.rotation,
+            animal.rotation - Math.PI / 2.0,
             'rgb(255, 255, 255)',
         );
 
@@ -271,8 +271,7 @@ function redraw() {
             const angleFrom =
                   animal.rotation
                   - config.eye_fov_angle / 2.0
-                  + cellId * anglePerCell
-                  + Math.PI / 2.0;
+                  + cellId * anglePerCell;
 
             const angleTo = angleFrom + anglePerCell;
             const energy = animal.vision[cellId];
```
... fixes all of the issues.

Still, I have to investigate what I don't understand about my calculations, then 😄

**Comment by Patryk27** [comment]
Okie, got the offender - it seems that `eye.rs` should have:
```rust
let angle = na::Rotation2::rotation_between(&na::Vector2::y(), &vec).angle();
```
... instead of `na::Vector2::x()`; this is the only fix needed, rest of the calculations are correct then (it seems!).

It's probably a remnant of me fixing https://github.com/Patryk27/website/issues/11 😅

**Comment by yovanoc** [comment]
![image](https://user-images.githubusercontent.com/7302317/227770495-75f59e13-f854-40a9-9bc5-327efe854393.png)

OH YES perfect ! But all eye.rs tests are failing now x)

**Comment by Patryk27** [comment]
Yeah, I'll try to prepare the updated version today :smile:

**Comment by yovanoc** [comment]
oh nice man ! but look

![image](https://user-images.githubusercontent.com/7302317/227785996-aec28b97-6d26-4449-a81f-76f004fbc730.png)


![image](https://user-images.githubusercontent.com/7302317/227786006-8751dd9c-ef57-46ff-9b5b-fc264dd0d20c.png)

if -90 degrees is on the right, then yeah rot 0 is to the top ?

**Comment by Patryk27** [comment]
Oh, that's interesting - I guess there's no food in front of that birdie that it could see, right? (i.e. it accidentally sees the food on its left here)

**Comment by yovanoc** [comment]
No sorry it's normal for the food but I speak about the -90 degrees rotation here, is pointing to the right good ?  so 0 is top not right

**Comment by Patryk27** [comment]
I see - yes, rotation seems alright here: rotation of zero = fly downward, and then it goes clockwise, so:

- `rot = 0` => down,
- `rot = PI/2` => left,
- `rot = PI` => up,
- `rot = 3/2 PI` (or, depending how you look at it, `rot = -PI/2`) => right.

**Comment by yovanoc** [comment]
Ok perfect !
