### ISSUE TITLE
`impl Trait` in type aliases is unstable

### ISSUE THREAD

**Issue by diggymacd** [Patryk27/shorelark#12]
Got this err at line 42 of Chromosome.rs.  Due to that IntoIterator() breaks a number of other places.  Surprised this hasn't popped up before.  Using rustc 1.68.2.

**Comment by Patryk27** [comment]
Hi, try with rustc 1.69 (or `nightly-2023-03-01`, as is in [`rust-toolchain`](https://github.com/Patryk27/shorelark/blob/22c8c29af2fbf68faad8486766efc3c665bb94b6/rust-toolchain)) 🙂

**Comment by diggymacd** [comment]
Tried those and still get the same error.  This is Windows 10 environment, BTW

**Comment by Patryk27** [comment]
I've just checked and everything seems to be working correctly on my Windows machine - could you post the results of `cargo --version`, `rustc --version` and `rustup --version`?

**Comment by diggymacd** [comment]
cargo and rustc are at 1.70.0 nightly.  rustup is at 1.25.2.  I did try rustc and cargo at 1.69.0

**Comment by Patryk27** [comment]
Ah, it seems that they've renamed `#![feature(type_alias_impl_trait)]` into `#![feature(impl_trait_in_assoc_type)]` - I've adjusted the code now so if you `git pull`, everything should work 🙂 

Thanks for reporting!
