### ISSUE TITLE
Tutorial: Eye angle to axis

### ISSUE THREAD

**Issue by visviva** [Patryk27/shorelark#13]
Awesome tutorial. I really love it. 

I think I found a small misunderstanding in the tutorial. In the explanation of  `process_vision` of `eye` it says at the second point where the angles are handled:
```rust
    // Returns vector's direction relative to the X axis, that is:
    //
    //   --> = 0° = 0
    //
    //    |  = 90° = PI / 2
    //    v
    //
    //   <--- = 180° = PI
    //
    // (if you've been measuring rotations before - this is atan2
    // in disguise.)
    let angle = na::Rotation2::rotation_between(
        &na::Vector2::y(),
        &vec,
    ).angle();
```
According to the code, it should explain the vector's direction according to the **Y** axis.

See also: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b7024ce656547f3095bc35dbadd36a41

**Comment by Patryk27** [comment]
Thanks for reporting, fixed! 🚀
