### ISSUE TITLE
Any update of part4?

### ISSUE THREAD

**Issue by ISeekTruth** [Patryk27/shorelark#7]
Thank your write  `the learning-to-fly `series, I am waiting for part4.

**Comment by Patryk27** [comment]
Hi 🙂 I'm writing it at the moment - it just takes a bit longer than I anticipated 😄

**Comment by ISeekTruth** [comment]
Good job! 👍

**Comment by ISeekTruth** [comment]
By the way, the blog part2 need to add `rust-toolchain` config for using `#![feature(min_type_alias_impl_trait)]`

**Comment by Patryk27** [comment]
Fixed, thanks :-)

**Comment by Patryk27** [comment]
Part 4 is live: https://pwy.io/en/posts/learning-to-fly-pt4/ :rocket:
