### ISSUE TITLE
Add license file and/or SPDX tag

### ISSUE THREAD

**Issue by AlexanderStein** [Patryk27/shorelark#8]
I know the `README.md` states this is licensed in `MIT`, but it would be better to have an explicit `LICENSE.txt` file. There are several variants of MIT license, so which is it?
Even better to have an [SPDX tag](https://spdx.dev/) in each source file.

**Comment by Patryk27** [comment]
Hi, thanks for pointing it out - I've added a `LICENSE` file now; if something's still missing or underspecified, please let me know 🙂
